with-expecter: true
dir: "{{.InterfaceDir}}/mocks"
filename: "mock_{{.InterfaceNameSnake}}.go"
outpkg: "mocks"
mockname: "{{.InterfaceName}}"
resolve-type-alias: False
issue-845-fix: True

packages:
    github.com/restinbass/payment-service/internal/service:
        config:
            include-regex: ".*Service"

    github.com/restinbass/payment-service/internal/repository:
        config:
            include-regex: ".*Repository"
